Disable env deployments temporarily for app sec testing (#451)

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -69,193 +69,193 @@ jobs:
       additional_docker_build_args: --secret id=sentry,env=SENTRY_AUTH_TOKEN
       push: ${{ inputs.push || true }}
       docker_multiplatform: true
-  deploy_dev:
-    name: Deploy to the development environment
-    needs:
-      - build
-      - helm_lint
-    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2 # WORKFLOW_VERSION
-    secrets: inherit
-    with:
-      environment: 'dev'
-      app_version: '${{ needs.build.outputs.app_version }}'
-      helm_timeout: '10m'
-  e2e-tests:
-    name: Run E2E tests against dev
-    needs:
-      - deploy_dev
-    timeout-minutes: 60
-    runs-on: [ self-hosted, Linux, X64, hmpps-github-actions-runner ]
-    env:
-      MANAGE_AND_DELIVER_URL: https://accredited-programmes-manage-and-deliver-dev.hmpps.service.justice.gov.uk
-      HMPPS_COMMUNITY_AUTH_USERNAME: ${{ secrets.HMPPS_COMMUNITY_AUTH_USERNAME }}
-      HMPPS_COMMUNITY_AUTH_PASSWORD: ${{ secrets.HMPPS_COMMUNITY_AUTH_PASSWORD }}
-    steps:
-      - name: Checkout main repo
-        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
+  # deploy_dev:
+  #   name: Deploy to the development environment
+  #   needs:
+  #     - build
+  #     - helm_lint
+  #   uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2 # WORKFLOW_VERSION
+  #   secrets: inherit
+  #   with:
+  #     environment: 'dev'
+  #     app_version: '${{ needs.build.outputs.app_version }}'
+  #     helm_timeout: '10m'
+  # e2e-tests:
+  #   name: Run E2E tests against dev
+  #   needs:
+  #     - deploy_dev
+  #   timeout-minutes: 60
+  #   runs-on: [ self-hosted, Linux, X64, hmpps-github-actions-runner ]
+  #   env:
+  #     MANAGE_AND_DELIVER_URL: https://accredited-programmes-manage-and-deliver-dev.hmpps.service.justice.gov.uk
+  #     HMPPS_COMMUNITY_AUTH_USERNAME: ${{ secrets.HMPPS_COMMUNITY_AUTH_USERNAME }}
+  #     HMPPS_COMMUNITY_AUTH_PASSWORD: ${{ secrets.HMPPS_COMMUNITY_AUTH_PASSWORD }}
+  #   steps:
+  #     - name: Checkout main repo
+  #       uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
 
-      - name: Checkout e2e tests repo
-        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
-        with:
-          repository: ministryofjustice/hmpps-accredited-programmes-manage-and-deliver-e2e-tests
-          path: hmpps-accredited-programmes-manage-and-deliver-e2e-tests
-          ref: main
+  #     - name: Checkout e2e tests repo
+  #       uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
+  #       with:
+  #         repository: ministryofjustice/hmpps-accredited-programmes-manage-and-deliver-e2e-tests
+  #         path: hmpps-accredited-programmes-manage-and-deliver-e2e-tests
+  #         ref: main
 
-      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
-        with:
-          node-version: lts/*
+  #     - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
+  #       with:
+  #         node-version: lts/*
 
-      - name: Install dependencies
-        working-directory: ./hmpps-accredited-programmes-manage-and-deliver-e2e-tests
-        run: npm ci
+  #     - name: Install dependencies
+  #       working-directory: ./hmpps-accredited-programmes-manage-and-deliver-e2e-tests
+  #       run: npm ci
 
-      - name: Install Playwright Browsers
-        working-directory: ./hmpps-accredited-programmes-manage-and-deliver-e2e-tests
-        run: npx playwright install
+  #     - name: Install Playwright Browsers
+  #       working-directory: ./hmpps-accredited-programmes-manage-and-deliver-e2e-tests
+  #       run: npx playwright install
 
-      - name: Run Playwright tests
-        id: playwright-tests
-        working-directory: ./hmpps-accredited-programmes-manage-and-deliver-e2e-tests
-        run: npx playwright test
+  #     - name: Run Playwright tests
+  #       id: playwright-tests
+  #       working-directory: ./hmpps-accredited-programmes-manage-and-deliver-e2e-tests
+  #       run: npx playwright test
 
-      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
-        if: ${{ !cancelled() }}
-        with:
-          name: playwright-report-${{ github.run_id }}
-          path: hmpps-accredited-programmes-manage-and-deliver-e2e-tests/playwright-report/
-          retention-days: 30
+  #     - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
+  #       if: ${{ !cancelled() }}
+  #       with:
+  #         name: playwright-report-${{ github.run_id }}
+  #         path: hmpps-accredited-programmes-manage-and-deliver-e2e-tests/playwright-report/
+  #         retention-days: 30
 
-      - name: Send a failure slack message
-        if: failure()
-        uses: slackapi/slack-github-action@af78098f536edbc4de71162a307590698245be95
-        with:
-          method: chat.postMessage
-          token: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}
-          payload: |
-            channel: hmpps_accredited_programmes_manage_and_deliver_alerts
-            text: "E2E Tests Failed"
-            blocks:
-              - type: "section"
-                text:
-                  type: "mrkdwn"
-                  text: ":x: *E2E Tests Failed*\n\n*Repository:* ${{ github.repository }}\n*Workflow:* ${{ github.workflow }}\n\n:page_facing_up: Playwright report available in workflow artifacts"
-              - type: "divider"
-              - type: "actions"
-                elements:
-                  - type: "button"
-                    text:
-                      type: "plain_text"
-                      text: "View Workflow"
-                    url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-  deploy_preprod:
-    name: Deploy to pre-production environment
-    needs:
-      - build
-      - deploy_dev
-    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2 # WORKFLOW_VERSION
-    secrets: inherit
-    with:
-      environment: 'preprod'
-      app_version: '${{ needs.build.outputs.app_version }}'
-  notify_for_prod_approval:
-    needs:
-      - build
-      - deploy_preprod
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
-      - name: Get PR information
-        id: pr-info
-        run: |
-          # Get the commit SHA from the last commit
-          # See https://docs.github.com/en/webhooks/webhook-events-and-payloads#workflow_run
-          COMMIT_SHA="${{ github.sha }}"
+  #     - name: Send a failure slack message
+  #       if: failure()
+  #       uses: slackapi/slack-github-action@af78098f536edbc4de71162a307590698245be95
+  #       with:
+  #         method: chat.postMessage
+  #         token: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}
+  #         payload: |
+  #           channel: hmpps_accredited_programmes_manage_and_deliver_alerts
+  #           text: "E2E Tests Failed"
+  #           blocks:
+  #             - type: "section"
+  #               text:
+  #                 type: "mrkdwn"
+  #                 text: ":x: *E2E Tests Failed*\n\n*Repository:* ${{ github.repository }}\n*Workflow:* ${{ github.workflow }}\n\n:page_facing_up: Playwright report available in workflow artifacts"
+  #             - type: "divider"
+  #             - type: "actions"
+  #               elements:
+  #                 - type: "button"
+  #                   text:
+  #                     type: "plain_text"
+  #                     text: "View Workflow"
+  #                   url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+  # deploy_preprod:
+  #   name: Deploy to pre-production environment
+  #   needs:
+  #     - build
+  #     - deploy_dev
+  #   uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2 # WORKFLOW_VERSION
+  #   secrets: inherit
+  #   with:
+  #     environment: 'preprod'
+  #     app_version: '${{ needs.build.outputs.app_version }}'
+  # notify_for_prod_approval:
+  #   needs:
+  #     - build
+  #     - deploy_preprod
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
+  #     - name: Get PR information
+  #       id: pr-info
+  #       run: |
+  #         # Get the commit SHA from the last commit
+  #         # See https://docs.github.com/en/webhooks/webhook-events-and-payloads#workflow_run
+  #         COMMIT_SHA="${{ github.sha }}"
 
-          # Get the first line of the most recent commit message
-          COMMIT_MESSAGE=$(git log -1 --pretty=%B "$COMMIT_SHA" | head -n 1)
-          echo "commit_message=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
+  #         # Get the first line of the most recent commit message
+  #         COMMIT_MESSAGE=$(git log -1 --pretty=%B "$COMMIT_SHA" | head -n 1)
+  #         echo "commit_message=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
 
-          # Use the GitHub CLI to get the PR associated with this commit, its number, title, and author
-          PR_INFO=$(gh pr list --search "$COMMIT_SHA" --json number,title,author --jq '.[0]')
-          PR_NUMBER=$(echo "$PR_INFO" | jq -r '.number')
-          PR_TITLE=$(echo "$PR_INFO" | jq -r '.title')
+  #         # Use the GitHub CLI to get the PR associated with this commit, its number, title, and author
+  #         PR_INFO=$(gh pr list --search "$COMMIT_SHA" --json number,title,author --jq '.[0]')
+  #         PR_NUMBER=$(echo "$PR_INFO" | jq -r '.number')
+  #         PR_TITLE=$(echo "$PR_INFO" | jq -r '.title')
 
-          # The author is the author of the commit
-          PR_AUTHOR="${{ github.actor}}"
+  #         # The author is the author of the commit
+  #         PR_AUTHOR="${{ github.actor}}"
 
-          echo "pr_author=$PR_AUTHOR" >> $GITHUB_OUTPUT
-          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
-          echo "pr_title=$PR_TITLE" >> $GITHUB_OUTPUT
-        env:
-          GH_TOKEN: ${{ github.token }}
-      - name: Map GitHub user to Slack ID
-        id: slack-mapping
-        run: |
-          # Parse the GitHub to Slack mapping (expecting JSON format)
-          GITHUB_USERNAME="${{ github.actor }}"
-          USER_MAPPING='${{ vars.GH_TO_SLACK_MAPPING }}'
+  #         echo "pr_author=$PR_AUTHOR" >> $GITHUB_OUTPUT
+  #         echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
+  #         echo "pr_title=$PR_TITLE" >> $GITHUB_OUTPUT
+  #       env:
+  #         GH_TOKEN: ${{ github.token }}
+  #     - name: Map GitHub user to Slack ID
+  #       id: slack-mapping
+  #       run: |
+  #         # Parse the GitHub to Slack mapping (expecting JSON format)
+  #         GITHUB_USERNAME="${{ github.actor }}"
+  #         USER_MAPPING='${{ vars.GH_TO_SLACK_MAPPING }}'
 
-          if [[ "$USER_MAPPING" == "" ]]; then
-            echo "Warning: GH_TO_SLACK_MAPPING not configured"
-            SLACK_USER_ID="unknown"
-          else
-            SLACK_USER_ID=$(echo "$USER_MAPPING" | jq -r --arg user "$GITHUB_USERNAME" '.[$user] // "unknown"')
-          fi
+  #         if [[ "$USER_MAPPING" == "" ]]; then
+  #           echo "Warning: GH_TO_SLACK_MAPPING not configured"
+  #           SLACK_USER_ID="unknown"
+  #         else
+  #           SLACK_USER_ID=$(echo "$USER_MAPPING" | jq -r --arg user "$GITHUB_USERNAME" '.[$user] // "unknown"')
+  #         fi
 
-          echo "slack_user_id=$SLACK_USER_ID" >> $GITHUB_OUTPUT
-      - name: Generate the Approval link
-        id: approval-link
-        run: |
-          # Create link to the workflow that needs approval
-          APPROVAL_LINK="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+  #         echo "slack_user_id=$SLACK_USER_ID" >> $GITHUB_OUTPUT
+  #     - name: Generate the Approval link
+  #       id: approval-link
+  #       run: |
+  #         # Create link to the workflow that needs approval
+  #         APPROVAL_LINK="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
 
-          echo "Approval Link: $APPROVAL_LINK"
-          echo "approval_link=$APPROVAL_LINK" >> $GITHUB_OUTPUT
-      - name: Send Slack notification
-        run: |
-          # Prepare the JSON payload
-          PAYLOAD=$(jq -n \
-            --arg link "${{ steps.approval-link.outputs.approval_link }}" \
-            --arg slack_user "${{ steps.slack-mapping.outputs.slack_user_id }}" \
-            --arg pr_name "${{ steps.pr-info.outputs.pr_title }}" \
-            --arg pr_number "${{ steps.pr-info.outputs.pr_number }}" \
-            --arg github_user "${{ github.actor }}" \
-            --arg repo "${{ github.repository }}" \
-            '{
-              link_to_approval_step: $link,
-              developer_to_tag_slack_user_id: $slack_user,
-              human_readable_pr_name: $pr_name,
-              pr_number: $pr_number,
-              github_username: $github_user,
-              repository: $repo,
-              timestamp: now
-            }')
+  #         echo "Approval Link: $APPROVAL_LINK"
+  #         echo "approval_link=$APPROVAL_LINK" >> $GITHUB_OUTPUT
+  #     - name: Send Slack notification
+  #       run: |
+  #         # Prepare the JSON payload
+  #         PAYLOAD=$(jq -n \
+  #           --arg link "${{ steps.approval-link.outputs.approval_link }}" \
+  #           --arg slack_user "${{ steps.slack-mapping.outputs.slack_user_id }}" \
+  #           --arg pr_name "${{ steps.pr-info.outputs.pr_title }}" \
+  #           --arg pr_number "${{ steps.pr-info.outputs.pr_number }}" \
+  #           --arg github_user "${{ github.actor }}" \
+  #           --arg repo "${{ github.repository }}" \
+  #           '{
+  #             link_to_approval_step: $link,
+  #             developer_to_tag_slack_user_id: $slack_user,
+  #             human_readable_pr_name: $pr_name,
+  #             pr_number: $pr_number,
+  #             github_username: $github_user,
+  #             repository: $repo,
+  #             timestamp: now
+  #           }')
 
-          # Send the webhook request
-          curl -X POST \
-            -H "Content-Type: application/json" \
-            -d "$PAYLOAD" \
-            "${{ secrets.SLACK_WEBHOOK_URL }}" \
-            --fail \
-            --show-error \
-            --silent
+  #         # Send the webhook request
+  #         curl -X POST \
+  #           -H "Content-Type: application/json" \
+  #           -d "$PAYLOAD" \
+  #           "${{ secrets.SLACK_WEBHOOK_URL }}" \
+  #           --fail \
+  #           --show-error \
+  #           --silent
 
-          if [[ $? -eq 0 ]]; then
-            echo "✅ Slack notification sent successfully"
-          else
-            echo "❌ Failed to send Slack notification"
-            echo "Please check the GH_TO_SLACK_MAPPING variable for user "${{ github.actor }}" and SLACK_WEBHOOK_URL secret."
-            exit 1
-          fi
-  deploy_prod:
-    name: Deploy to production environment
-    needs:
-      - build
-      - deploy_preprod
-    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2 # WORKFLOW_VERSION
-    secrets: inherit
-    with:
-      environment: 'prod'
-      app_version: '${{ needs.build.outputs.app_version }}'
-      slack_notification: 'true' # Value set in project variables in GitHub
+  #         if [[ $? -eq 0 ]]; then
+  #           echo "✅ Slack notification sent successfully"
+  #         else
+  #           echo "❌ Failed to send Slack notification"
+  #           echo "Please check the GH_TO_SLACK_MAPPING variable for user "${{ github.actor }}" and SLACK_WEBHOOK_URL secret."
+  #           exit 1
+  #         fi
+  # deploy_prod:
+  #   name: Deploy to production environment
+  #   needs:
+  #     - build
+  #     - deploy_preprod
+  #   uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2 # WORKFLOW_VERSION
+  #   secrets: inherit
+  #   with:
+  #     environment: 'prod'
+  #     app_version: '${{ needs.build.outputs.app_version }}'
+  #     slack_notification: 'true' # Value set in project variables in GitHub
